-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here

-- CMake Tools keymaps
vim.keymap.set("n", "<leader>ccg", "<cmd>CMakeGenerate<cr>", { desc = "CMake Generate" })
vim.keymap.set("n", "<leader>ccb", "<cmd>CMakeBuild<cr>", { desc = "CMake Build" })
vim.keymap.set("n", "<leader>ccf", "<cmd>CMakeBuildCurrentFile<cr>", { desc = "CMake Build Current File" })
vim.keymap.set("n", "<leader>ccr", "<cmd>CMakeRun<cr>", { desc = "CMake Run" })
vim.keymap.set("n", "<leader>ccR", "<cmd>CMakeRunCurrentFile<cr>", { desc = "CMake Run Current File" })
vim.keymap.set("n", "<leader>ccd", "<cmd>CMakeDebug<cr>", { desc = "CMake Debug" })
vim.keymap.set("n", "<leader>ccD", "<cmd>CMakeDebugCurrentFile<cr>", { desc = "CMake Debug Current File" })
vim.keymap.set("n", "<leader>cct", "<cmd>CMakeRunTest<cr>", { desc = "CMake Run Test" })
vim.keymap.set("n", "<leader>cca", "<cmd>CMakeLaunchArgs<cr>", { desc = "CMake Launch Args" })
vim.keymap.set("n", "<leader>ccT", "<cmd>CMakeSelectBuildType<cr>", { desc = "CMake Select Build Type" })
vim.keymap.set("n", "<leader>ccs", "<cmd>CMakeSelectBuildTarget<cr>", { desc = "CMake Select Build Target" })
vim.keymap.set("n", "<leader>ccl", "<cmd>CMakeSelectLaunchTarget<cr>", { desc = "CMake Select Launch Target" })
vim.keymap.set("n", "<leader>cck", "<cmd>CMakeSelectKit<cr>", { desc = "CMake Select Kit" })
vim.keymap.set("n", "<leader>ccp", "<cmd>CMakeSelectConfigurePreset<cr>", { desc = "CMake Select Configure Preset" })
vim.keymap.set("n", "<leader>ccP", "<cmd>CMakeSelectBuildPreset<cr>", { desc = "CMake Select Build Preset" })
vim.keymap.set("n", "<leader>ccw", "<cmd>CMakeSelectCwd<cr>", { desc = "CMake Select Cwd" })
vim.keymap.set("n", "<leader>ccB", "<cmd>CMakeSelectBuildDir<cr>", { desc = "CMake Select Build Dir" })
vim.keymap.set("n", "<leader>cce", "<cmd>CMakeOpenExecutor<cr>", { desc = "CMake Open Executor" })
vim.keymap.set("n", "<leader>ccE", "<cmd>CMakeOpenRunner<cr>", { desc = "CMake Open Runner" })
vim.keymap.set("n", "<leader>ccc", "<cmd>CMakeOpenCache<cr>", { desc = "CMake Open Cache" })
vim.keymap.set("n", "<leader>cci", "<cmd>CMakeInstall<cr>", { desc = "CMake Install" })
vim.keymap.set("n", "<leader>ccC", "<cmd>CMakeClean<cr>", { desc = "CMake Clean" })
vim.keymap.set("n", "<leader>ccqb", "<cmd>CMakeQuickBuild<cr>", { desc = "CMake Quick Build" })
vim.keymap.set("n", "<leader>ccqr", "<cmd>CMakeQuickRun<cr>", { desc = "CMake Quick Run" })
vim.keymap.set("n", "<leader>ccqd", "<cmd>CMakeQuickDebug<cr>", { desc = "CMake Quick Debug" })
vim.keymap.set("n", "<leader>ccF", "<cmd>CMakeShowTargetFiles<cr>", { desc = "CMake Show Target Files" })
vim.keymap.set("n", "<leader>ccq", "<cmd>CMakeQuickStart<cr>", { desc = "CMake Quick Start" })
vim.keymap.set("n", "<leader>ccS", "<cmd>CMakeSettings<cr>", { desc = "CMake Settings" })
vim.keymap.set("n", "<leader>cco", "<cmd>CMakeTargetSettings<cr>", { desc = "CMake Target Settings" })
